### ISSUE TITLE
error: C:\GitHub\Projects\AudioAppDemo\Source\Main.cpp: 'ColourPanel' is a private member of 'foleys::StyleColourPropertyComponent'

### ISSUE THREAD

**Issue by ToxMox** [ffAudio/PluginGuiMagic#15]
Hi there. I haven't tried programming since the 1990s and I'm trying to get JUCE and PluginGuiMagic working. I get these same errors with the PluginGuiMagic example projects as well. I'm sure I'm doing something stupid.

Thanks for any kind of guidance here :)
![Projucer_20200314_133420](https://user-images.githubusercontent.com/22566356/76687288-e5356d00-65f8-11ea-9ce5-7c50b2106f2a.png)

**Comment by ToxMox** [comment]
Ok I think I may have discovered my issue. I only cloned this repo and not the foleys_gui_magic repo. Cloning now. I have a feeling that's the problem. All kinds of nice instructions there too that I shall read haha.

**Comment by ffAudio** [comment]
That's great :-) yes, you will need all submodules, which is the JUCE (you can use your existing JUCE, in which case you have to adapt the paths on the modules page) and the foleys_gui_magic.
Please make sure, if you don't use the git submodule command, that the name of the folder is foleys_gui_magic. Sometimes git download appends the branchname, which makes Projucer fall over.
And I didn't test building in Projucer, since that is known to produce issues. The recommendation of the JUCE team is to compile in your IDE, in your case Visual Studio.

Good luck, let me know if that works.

**Comment by ToxMox** [comment]
Ah! Building in Visual Studio works. Neat! Thank you. Going to have a lot of playing around to do now :)

**Comment by ToxMox** [comment]
I have to say. Very impressive project you've made here. Will make building a gui so much easier!

**Comment by ffAudio** [comment]
Glad it works. Looking forward to what stuff you will build with it :-)
