### ISSUE TITLE
Crash in FoleysSynth when editing  the oscillator section

### ISSUE THREAD

**Issue by sletz** [ffAudio/PluginGuiMagic#26]
<img width="1337" alt="Capture d’écran 2020-12-03 à 10 38 53" src="https://user-images.githubusercontent.com/1430487/100992302-4f5dbb80-3554-11eb-91cd-87c260ed6ce1.png">

**Comment by ffAudio** [comment]
Thanks for raising this issue.
There is actually already a fix on develop: https://github.com/ffAudio/foleys_gui_magic/commit/485181da11d5f88b888d78f5d5c4876d03e0ab7d

I had hoped to squeeze a few more features into that release, but maybe it should just be shipped, since this drop shadow thing is annoying.

**Comment by sletz** [comment]
OK, thanks.

**Comment by ffAudio** [comment]
The fix is now merged to v1.2.7 (master branch)
https://github.com/ffAudio/foleys_gui_magic/tree/v1.2.7
Hope this fixes the issue, if it still occurs, please reopen.
